# Generated by Django 2.0.1 on 2018-01-18 19:27

from django.db import migrations, models
import file_processing.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='currency',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='supplier_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=file_processing.models.supplier_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='filemodel',
            unique_together={('supplier_id', 'date', 'currency')},
        ),
    ]
