# Generated by Django 2.0.1 on 2018-01-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0002_auto_20180118_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('success', 'Success'), ('fail', 'Fail')], default='pending', max_length=25),
        ),
    ]
