# Generated by Django 2.0.1 on 2018-01-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0003_filemodel_processing_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filemodel',
            unique_together=set(),
        ),
    ]
